// Dashboard constants public API
export {
  MOCK_API_DELAY,
  MOCK_ERROR_RATE,
  QUIZ_GRID_COLUMNS,
  DIFFICULTY_COLORS,
  SOURCE_LABELS,
  QUERY_KEYS,
  DASHBOARD_ERROR_MESSAGES,
  SCORE_THRESHOLDS,
  SCORE_COLORS,
  RECENT_ACTIVITY_LIMIT,
  CHART_CONFIG,
  TIME_FORMAT,
} from './dashboardConstants';
