// Auth constants public API
export {
  MAX_INPUT_LENGTH,
  MAX_NAME_LENGTH,
  MIN_PASSWORD_LENGTH,
  AUTH_VALIDATION_MESSAGES,
  AUTH_ERROR_MESSAGES,
  AUTH_STORAGE_KEYS,
  AUTH_MOCK_DELAYS,
  INITIAL_AUTH_FORM_STATE,
  INITIAL_FORGOT_PASSWORD_STATE,
} from './authConstants';
